config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :videos, only: [:new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  get 'about-us', to: 'pages#about'
  get 'contact', to: 'pages#contact'
end

app/models/video.rb
class Video < ApplicationRecord
  #belongs_to :user

  mount_uploader :file, VideoUploader
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def new
    @video = Video.new
  end

  def create
    obj = S3_BUCKET.bucket('bucket_name').object('key')
    location = "public/uploads/video/file/19/#{video_params[:file].original_filename}"

    @video = Video.new(video_params)
    @video.user_id = current_user.id

    respond_to do |format|
      if @video.save
        obj.upload_file(location, acl: 'public-read')
        format.html { redirect_to root_path, notice: "Video was successfully created." }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:file)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/new.html.erb
<h1>Ssup peeps?</h1>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.name %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <h1>New Video</h1>

  <%= render 'form', video: @video %>

  <%= link_to 'Back', videos_path %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>